name: build-push-release

on:
  release:
    types: [published]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Echo ${GITHUB_REF_NAME}
        run: echo ${GITHUB_REF_NAME}
      - name: Echo ${GITHUB_REF_NAME:1}
        run: echo ${GITHUB_REF_NAME:1}
      - name: Echo ${{ github.event.release.tag_name }}
        run: echo ${{ github.event.release.tag_name }}
      - name: Write Tag to ENV variable
        run: echo "LABEL_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Get Docker Labels from python script
        run: python .github/workflows/docker_labels.py
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: ./
          file: docker/images/automatic/Dockerfile
          builder: ${{ steps.buildx.outputs.name }}
          push: true
          tags: |
            cxnt/automatic-actions:${GITHUB_REF_NAME:1}
          build-args: |
            LABEL_VERSION=agent:${{ env.LABEL_VERSION }}
