name: Upload PyPI and Docker

on:
  release:
    types: [published]

jobs:
  deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - run: echo ${{ github.ref }}
    - run: echo ${{ github.ref.name }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install build

    - name: Build package
      run: python -m build
    - name: Publish package
      uses: pypa/gh-action-pypi-publish@27b31702a0e7fc50959f5ad993c78deac1bdfc29
      with:
        user: ${{ secrets.PYPI_USERNAME }}
        password: ${{ secrets.PYPI_PASSWORD }}

#    - run: echo ${{ steps.tag.outputs.result }}

    - name: Delay for PyPI publish
      uses: jakejarvis/wait-action@master
      with:
        time: '10s'


    - name: Build and Push Docker Image
      uses: mr-smithers-excellent/docker-build-push@v5
      with:
        image: cxnt/automatic-actions
        addLatest: true
        dockerfile: "docker/Dockerfile"
        registry: docker.io
        buildArgs: |
          cur_ref_name=${{ github.ref }}
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

#      env:
##        TAG2: ${{ GITHUB_REF_NAME }}
#        TAG3: ${{ env.GITHUB_REF_NAME }}
##        TAG: ${{ v0.0.87 }}
