name: Push Docker Image Import

on:
  release:
    types: [published]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.8"

      - run: echo ${GITHUB_REF_NAME:1}

      - run: echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV

      - run: |
          echo $RELEASE_VERSION
          echo ${{ env.RELEASE_VERSION }}

      - name: Build and Push Docker Image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: cxnt/automatic-actions
          tags: ${{ env.RELEASE_VERSION }}
          addLatest: true
          dockerfile: "docker/images/import/Dockerfile"
          registry: docker.io
          buildArgs: |
            tag_ref_name=${{ github.ref_name }}
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
