name: Slack Notification Demo

on:
  release:
    types: [published]

jobs:
  slackNotification:
    name: Slack Notification
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Write Tag to ENV variable
      run: echo "RELEASE_VERSION=${GITHUB_REF_NAME:1}" >> $GITHUB_ENV
      
    - name: Slack Notification
      uses: rtCamp/action-slack-notify@v2
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
        SLACK_USERNAME: supervisely-notify
        SLACK_ICON: https://i.imgur.com/lannAET.png
        SLACK_COLOR: ${{ job.status }}
        SLACK_TITLE: New Supervisely ${{ env.RELEASE_VERSION }} released!
        SLACK_MESSAGE: ${{ github.event.release.name }}
        
